# Generated by Django 3.2 on 2022-04-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_composition', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='DrugType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Manufacturer Name')),
            ],
        ),
        migrations.CreateModel(
            name='PackSizeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('sku_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='SKU ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Drug Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('rx_required', models.BooleanField(null=True, verbose_name='Prescription Required')),
                ('is_discontinued', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='drugs.datasource')),
                ('manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='drugs.manufacturer')),
                ('pack_size_label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packsize', to='drugs.packsizelabel')),
                ('short_composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composition', to='drugs.drugcomposition')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drug_type', to='drugs.drugtype')),
            ],
        ),
    ]
