# Generated by Django 3.2 on 2022-04-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='url',
            new_name='source_url',
        ),
    ]
