# Generated by Django 3.2 on 2022-04-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugtype',
            old_name='type',
            new_name='type_of_drug',
        ),
    ]
