# Generated by Django 3.2 on 2022-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='drugcomposition',
            name='short_composition',
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='drugtype',
            name='type',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='packsizelabel',
            name='label',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
