# Generated by Django 4.0.3 on 2022-04-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20220409_0819'),
        ('drugs', '0002_rename_type_drugtype_type_of_drug'),
    ]

    operations = [
    ]
